name: 환경변수
values:
  - key: baseUrl
    value: http://localhost:8080
  - key: userA_email
    value: userA@example.com
  - key: userA_password
    value: password123
  - key: userA_id
    value: ''
  - key: userA_token
    value: ''
  - key: userA_refresh
    value: ''
  - key: userB_email
    value: userB@example.com
  - key: userB_password
    value: password123
  - key: userB_id
    value: ''
  - key: userB_token
    value: ''
  - key: userB_refresh
    value: ''
  - key: creatorC_email
    value: creatorC@example.com
  - key: creatorC_password
    value: password123
  - key: creatorC_id
    value: ''
  - key: creatorC_token
    value: ''
  - key: creatorC_refresh
    value: ''
  - key: postId
    value: ''
  - key: commentId
    value: ''
  - key: showId
    value: '1'
  - key: seatId
    value: ''
  - key: soldOutSeatId
    value: ''
  - key: queueRank
    value: ''
  - key: queueIsReady
    value: ''
  - key: orderId
    value: ''
  - key: paymentId
    value: ''
  - key: idempotencyKey
    value: ''
color: 0
