server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: feed-service
          uri: lb://FEED-SERVICE
          predicates:
            - Path=/api/v1/feeds/**
        - id: ticketing-service
          uri: lb://TICKETING-SERVICE
          predicates:
            - Path=/api/v1/tickets/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted