server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/

management:
  tracing:
    sampling:
      probability: 0.1     # 100% → 10%. 부하 중 Zipkin 추적